### ISSUE TITLE
cheerio convert dom to html is not expect

### ISSUE THREAD

**Issue by janryWang** [cheeriojs/cheerio#1006]
check this
```
var $ = cheerio.load(`<div class='{"name":"value"}'>hello</div>`)
$.html() 
>>> <div class="{"name":"value"}">hello</div>`
```

**Comment by mehdi-cit** [comment]
Hello @janryWang 
I'm having a similar problem. Where you able to find a solution?

**Comment by mehdi-cit** [comment]
You may want to look as function function `formatAttrs(attributes, opts) {`
In npm module 'dom-serializer' which is one of cheerio's dependencies. More specifically the line below:
`output += key + '="' + (opts.decodeEntities ? entities.encodeXML(value) : value) + '"';

**Comment by janryWang** [comment]
@mehdi-cit So, how to solve this problem?

**Comment by mehdi-cit** [comment]
@janryWang 
I am no longer using cheerio (for other reasons) so I have not solved the problem per see.
However, I looked into the code and the line I refer to above is where the attribute value gets written within double quotes. So that could be your starting point.
Sorry if I could not be of more help.

**Comment by ArmorDarks** [comment]
Same issue here. And quite unfortunate issue...

**Comment by Prinzhorn** [comment]
I've been searching through all relevant issues and this one is still open. I'm having the same problem as #85, #319, #338, #720 and #866. There doesn't seem to be a solution that satisfies all of them. That is: create a valid attribute but don't touch Unicode characters.

```js
const cheerio = require('cheerio');

let html = `<html><head></head><body><div data-options='{"itemselector": ".entry"}'>Äpfel</div></body></html>`

console.log(cheerio.load(html).html());
console.log(cheerio.load(html, { decodeEntities: false }).html());
```

Output

```html
<!--The attribute is valid but Äpfel became &#xC4;pfel-->
<html><head></head><body><div data-options="{&quot;itemselector&quot;: &quot;.entry&quot;}">&#xC4;pfel</div></body></html>

<!--Äpfel are great but the attribute is broken-->
<html><head></head><body><div data-options="{"itemselector": ".entry"}">Äpfel</div></body></html>
```

I think these to attempted to fix the issue https://github.com/cheeriojs/dom-serializer/pull/33 https://github.com/fb55/entities/pull/28 but didn't make it.

It'd be sick if we can find a solution. And if it's a breaking change, I'd happily install 2.x instead of 1.x.

**Comment by fb55** [comment]
This should be resolved with the latest release!
