### ISSUE TITLE
Master and readme don't match public release

### ISSUE THREAD

**Issue by xymbol** [cheeriojs/cheerio#1029]
Just re-added `cheerio` in a project and got `1.0.0-rc.1` installed. As I was using the library in tests, it was relatively easy to notice breaking changes but, others may not have a similar experience. To my surprise, nor `master` nor the docs reflected these changes.

Currently, the most simple example from the [readme](https://github.com/cheeriojs/cheerio/blob/f21ffef971826d1ba64ccbdf96adbc44964d30c5/Readme.md#L26-L33), is broken:

```javascript
var assert = require('assert');
var cheerio = require('cheerio');

describe('example from readme', function() {
  it('is broken', function() {
    var $ = cheerio.load('<h2 class="title">Hello world</h2>');
    $('h2.title').text('Hello there!');
    $('h2').addClass('welcome');
    assert.equal($.html(), '<h2 class="title welcome">Hello there!</h2>');
  });
});
```

Even the discussion around #1027 fails to fully address the changes with the `.load()` function signature. Unless is too late, I would suggest keeping the previous behavior of loading document fragments instead of complete documents.

Cheerio has been featured many times in books, talks, etc. Those materials can't be changed and, will be around for quite a while.

**Comment by jugglinmike** [comment]
Thanks for the report!

> Even the discussion around #1027 fails to fully address the changes with the
> .load() function signature.

Correct; that patch is incomplete. I've submitted a new patch which accounts
for these changes: https://github.com/cheeriojs/cheerio/pull/1033

> To my surprise, nor master nor the docs reflected these changes.

That's a great point. Once the pre-release documentation lands, we'll be
updating the project's "readme" file on the `master` branch to let folks know
where to find it.

> Unless is too late, I would suggest keeping the previous behavior of loading
> document fragments instead of complete documents.
>
> Cheerio has been featured many times in books, talks, etc. Those materials
> can't be changed and, will be around for quite a while.

It is by no means "too late," but this change is intentional. We recognized
that it is backwards-incompatible when we made it, but we feel the new behavior
is an improvement. And while this may invalidate some existing educational
material, that fact alone is not enough to block changes. For libraries, the
point of major releases is to iterate on more fundamental behavior; developers
who rely on open source code need to be comfortable with the possibility that
change occurs over time--especially for projects that have not reached version
1.0!

**Comment by xymbol** [comment]
>We recognized that it is backwards-incompatible when we made it, but we feel the new behavior
is an improvement.

Thanks for your reply!

Quick question re fragments, while the docs are in the works.

Would this be the new way to accomplish this?

```javascript
it('() : should preserve entities', function() {
  var options = {
    decodeEntities: false,
    useHtmlParser2: true
  };
  var $ = cheerio.load('<div>π &euro;</div><br>', options, false);
  $('div').addClass('foo');
  expect($.html(options)).to.equal('<div class="foo">π &euro;</div><br>');
});
```

Thanks in advance!

**Comment by jugglinmike** [comment]
Hmm, I'm not sure we want to commit to breaking backwards compatibility in that way. I've raised this issue with the maintainer of Parse5 over in gh-985

**Comment by xymbol** [comment]
@jugglinmike Awesome, thanks!
