### ISSUE TITLE
Minor issue, but switch the parameters passed into .each() please

### ISSUE THREAD

**Issue by JiniHendrix** [cheeriojs/cheerio#1053]
Come on, the tradition is (elem, index) not (index, elem)

**Comment by jugglinmike** [comment]
"Tradition" is a tricky word. If you are referring to the ECMAScript standard, then yes, it is certainly more common for the member to precede the index in parameter lists. However, [this project's explicit goal is to mimic the jQuery API](https://github.com/cheeriojs/cheerio/tree/c0096b150c01303f7e15d584e3a1648f52bd63c4#features), where [the reverse ordering has been observed since initial implementation](http://api.jquery.com/each/).
