### ISSUE TITLE
loaded object is different then .each's element?

### ISSUE THREAD

**Issue by epyx25** [cheeriojs/cheerio#1055]
```Javascript
const table = `
  <table>
    <tr>
      <td></td>
      <td class="with-link"><a href="www.foo.bar"></a></td>
    </tr>
  </table>
`
const row = `<td><a href="www.foo.bar"></a></td>`

class Scraper {
  htmlToDom(html) {
    return cheerio.load(html)
  }
  findHref(row) {
    return row('a').attr('href')
  }
}
const scraper = new Scraper()
const cheerioRow = scraper.htmlToDom(row)
// 1st case
console.log(scraper.findHref(cheerioRow))

// 2nd case
const cheerioTable = scraper.htmlToDom(table)
cheerioTable('tr').each(function() {
  //console.log(this)
  let td = cheerioTable(this).find('td.with-link')
  console.log(scraper.findHref(td))

})

```

https://jsbin.com/kodototope/edit?js,console
In the 1st case I load a string to cheerio, and Scraper's `findHref` handles it correctly.
In the 2nd case I loop through the table's rows, and I find the very same `td` . But it looks like the two object is different, because in the 2nd case I am getting 

> "TypeError: cell is not a function

from `findHref`.

Interestingly if I extract the html and load it again, it works: (https://jsbin.com/jehoxotusa/edit?js,console)

```Javascript
  let td = cheerioTable.html('td.with-link', this)
  console.log(scraper.findHref(scraper.htmlToDom(td))) 
```

**Comment by jugglinmike** [comment]
There seems to be some difference between the script you have shared and the script you are running--the reported error references a variable named "cell" which is not present in the provided script.

That said, I may still be able to help.

    const cheerioRow = scraper.htmlToDom(row)
    // 1st case
    console.log(scraper.findHref(cheerioRow))

The `cheerioRow` binding is the return value of Cheerio's static `load` method. This is a "selector function" that mimics the global function provided by the jQuery library. This example functions as expected because the `findHref` method uses this value as a function:

    findHref(row) {
      return row('a').attr('href')
    }


On the other hand, consider these two lines from the problem area:

    let td = cheerioTable(this).find('td.with-link')
    console.log(scraper.findHref(td))

Here, `td` is the return value of Cheerio's `find` method. This is a Cheerio object, not a function. That's why your `findHref` method throws an error.

There are a number of ways to resolve this. The most straightforward (and least disruptive) may be the definition of a new function that accepts a Cheerio object, e.g.:

    findHrefIn($row) {
      return $row.find('a').attr('href');
    }

...but this duplicates some of the logic in `findHref`. Hopefully you see what I'm getting at, though--I'll leave it to you to decide on a solution that works best for your project.

Since there's still a little uncertainty due to that `cell` variable, can you let me know if this addresses your problem? If so, I'd like to close this issue.

**Comment by epyx25** [comment]
@jugglinmike thanks!
