### ISSUE TITLE
[Question] Cannot get child node by selector

### ISSUE THREAD

**Issue by dinfer** [cheeriojs/cheerio#1068]
It's a bug? or the selector is incorrect?

```js
cheerio($).children('.mypics img').attr('src') // => undefined 
cheerio($).children('.mypics').children('img').attr('src') // = '//i1.hdfimg.com/mobi/images/img1.png'
```

full

```js
cheerio = require('cheerio')
const src = `    <div class="tlist clearfix">        <div class="mypics"><img src="//x.com/mobi/images/img1.png"/></div>        <div class="mytitle">            <
h3>h***</h3>            <p><span>*****</span>06.10 18:58</p>        </div>        <h5>*******</h5>    </div> `
const root = cheerio.load(src)
const item = root('.tlist')
$ = cheerio(item.last())
cheerio($).children('.mypics img').attr('src') // => undefined 
cheerio($).children('.mypics').children('img').attr('src') // => '//x.com/mobi/images/img1.png'
```

cheerio version `1.0.0-rc.2`

**Comment by jugglinmike** [comment]
The first argument of the `children` method acts as a filter on the children. The first query returns the empty set because none of the direct children of the `div` element match the selector `.mypics img`. If you would like to perform a deep search of the tree from that point, try using the `find` method instead.

(Also note that in your example, you could call `children` on the `item` method directory. Or even on the result of `item.last`, as in `item.last().children()`. In either case, wrapping the `$` querying function in a call to the function exported by the library isn't necessary.)

**Comment by dinfer** [comment]
thanks very much
