### ISSUE TITLE
How can I get json string from cheerio object?

### ISSUE THREAD

**Issue by wizardnet972** [cheeriojs/cheerio#1113]
not found anywhere.

How can I get json string from cheerio object? NOT OBJECT, but STRING

for example:
```
<xml>
  <some1></some1>
  <some2></some2>
</xml>
```

json (string):
```
xml {
 some1, 
 some2
}
```

**Comment by VulcanRav** [comment]
Hint: try 
`typeof $.xml();`

**Comment by wizardnet972** [comment]
NO.  $.xml() get me the xml as string. what I need is json.

**Comment by dbuezas** [comment]
Just walk the tree yourself and grab what you need on the way, the DOM is represented as a javascript object already in cheerio.
`
walk = (el) => ({ tagName: el.tagName, attribs: el.attribs, children: el.children.map(visit) }); 
JSON.stringify(walk($('html')[0]), null, 2);
`
if you want the doctype then start the walk on `$._root`. Technically you should use cheerio's getters instead of accessing the properties directly but whatever.

**Comment by VulcanRav** [comment]
@wizardnet972, I gave you the hint, I'm sorry you didn't understood it.

As @dbuezas pointed you, you simply use the [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) method on a string. So once you've converted your Cheerio object (normal js object) to a string (either $.xml() or $.html(), you're basically done.

**Comment by fb55** [comment]
Assuming this is solved!
