### ISSUE TITLE
Docs Examples Provide Incorrect Information

### ISSUE THREAD

**Issue by ilyaigpetrov** [cheeriojs/cheerio#1204]
Your examples are quite incorrect:
```js
'use strict';

const cheerio = require('cheerio')
const $ = cheerio.load('<h2 class="title">Hello world</h2>')

$('h2.title').text('Hello there!')
$('h2').addClass('welcome')

console.log($.html());
//EXPECTED: <h2 class="title welcome">Hello there!</h2>
//ACTUAL: <html><head></head><body><h2 class="title welcome">Hello there!</h2></body></html>
```
See expected vs actual. Fix the docs, please.

**Comment by AmeliaBR** [comment]
I also just stumbled on this issue.  Based on the documentation, I expected Cheerio to be able to work in document fragments. Instead the parser always treats the loaded document as a complete HTML file, and therefore inserts `<html>`, `<head>`, and `<body>` elements before any content elements.

Is this a recent change? Maybe with the parser? Perhaps there could be a new option to control it?

Regardless, the docs should reflect the default behavior.

PS, For anyone with a similar issue, I found that doing `$("body").html()` successfully extracts the content fragment.  (Although again: this is a docs error, since the docs say that this would return the _outer_ HTML for the body element, and it instead returns the _inner_ HTML.)

**Comment by thewheat** [comment]
Older versions `0.22.0`, `0.20.0` and `0.19.0` (haven't checked older versions) return without the extra tags

![image](https://user-images.githubusercontent.com/892961/66694873-28f31600-eceb-11e9-89e5-dbee29c1f230.png)

So affects `1.0.0-rc.1` to latest `1.0.0-rc.3`. Unsure if this is expected behaviour but but looking at the current Readme it has already been updated in [this PR](https://github.com/cheeriojs/cheerio/commit/ddd036d46a8a4583fc532c628d8a556edb13bd52) 👍 so looks like this issue can be closed

![image](https://user-images.githubusercontent.com/892961/66694886-4d4ef280-eceb-11e9-8b81-b7d73b24d825.png)
