### ISSUE TITLE
Update cheerio on NPM

### ISSUE THREAD

**Issue by jeroentvb** [cheeriojs/cheerio#1329]
Today I got prompted that one of my projects has a vulnerability. Upon investigation I noticed it comes from the lodash dependency in cheerio.

I saw that there has been a PR to update lodash (#1300) which was superfluous, but the newer lodash version is being used by cheerio on the v1.0.0 branch.
Unfortunately the update hasn't made it to NPM yet, so when I `npm install cheerio` I get the vulnerable version of lodash.

Could this tiny update be pushed to NPM please?

**Comment by cheshrkat** [comment]
FWIW I just tried a clean project...
```
npm init
npm i cheerio --save
npm audit
```
...and it's passing with cheerio `1.0.0-rc.3`. A project I've just updated from RC2 (which was getting alerts) is now happy in Snyk with RC3 as well.

**Comment by jeroentvb** [comment]
I forgot which command I used exactly (npm suggested it after running `npm audit`). But my project doesn't use the vulnerable version of lodash anymore.

Good to know that it doesn't get the vulnerable version of lodash when creating a new project.

**Comment by cheshrkat** [comment]
@jeroentvb probably `npm audit fix` which will update your lock file to the newer version. 

New projects might be ok since Cheerio's dependency is set to `^` (ie. auto-update minor versions), so I'm thinking fresh builds just get an updated version of lodash. It'd still be better to get an updated release, but the project seems a bit stalled in Release Candidate. Not sure why 🤔
