### ISSUE TITLE
Instance `$.html()` method will delete the element

### ISSUE THREAD

**Issue by lqzhgood** [cheeriojs/cheerio#1524]
```javascript
const cheerio = require("cheerio");

const html = `1<br>2<br>3<br>4<br>5<br>`;
const $ = cheerio.load(`<div id="_isWrap">${html}</div>`, { decodeEntities: false });

const nodeList = $("#_isWrap")[0].children;
const msgArr = [];

console.log('nodeList',nodeList, nodeList.length);   //  ====> 10
// 0: Node {type: "text", data: "1",}
// 1: Node {type: "tag", name: "br",}
// 2: Node {type: "text", data: "2",}
// 3: Node {type: "tag", name: "br",}
// 4: Node {type: "text", data: "3",}
// 5: Node {type: "tag", name: "br",}
// 6: Node {type: "text", data: "4",}
// 7: Node {type: "tag", name: "br",}
// 8: Node {type: "text", data: "5",}
// 9: Node {type: "tag", name: "br",}


for (let i = 0; i < nodeList.length; i++) {
    if (i % 2 === 0) {
        const n = nodeList[i];
        const nn = nodeList[i + 1];
        
        //   Problem points
        const $_inner = cheerio.load([n, nn], { decodeEntities: false });
        msgArr.push({
            html: $_inner.html(),
            text: $_inner.text(),
            index: i,
        });
       //   Problem points

    }
}

console.log('nodeList', nodeList, nodeList.length);// =====> 5   Shouldn't it be 10 here
// 0: Node {type: "text", data: "↵2",  }
// 1: Node {type: "tag", name: "br", }
// 2: Node {type: "text", data: "↵4" }
// 3: Node {type: "tag", name: "br", } 
// 4: Node {type: "text", data: "↵", }


console.log('msgArr', msgArr);
// 0: {html: "1<br>", text: "1",index:0}
// 1: {html: "3<br>", text: "3",index:2}
// 2: {html: "5<br>", text: "5",index:4}

```

Why  index [ 2,3 , 6,7 ] in `nodeList` was a deleted

**Comment by 5saviahv** [comment]
If you use `cheerio.load([n, nn])` it removes those `n` and `nn` elements from `nodeList` array, you should use `cheerio([n, nn])` instead.

**Comment by fb55** [comment]
Thanks for figuring this one out @5saviahv!

**Comment by lqzhgood** [comment]
What's the difference between `cheerio` and `cheerio.load`? I can't find the use of `cheerio` in the Api documentation.

**Comment by 5saviahv** [comment]
Since cheerio does not have browser who translates html pages like `jQuery` have. Cheerio have to use parsers and exposes it for user as `cheerio.load`. This function main task is create new document with root element but with creating it, removes all connections to other elements. Maybe you want extract iframe content. jQuery also has root element and you can access it, but it is usually created automatically when page loads.

if you use `cheerio` it behaves as wrapper, and creates snapshot, from elements, they keep their parents, and all childs and siblings. 

Plain `cheerio` object does not have root element and you can not search elements. With load you create new cheerio object with root element (with document).

```javascript
const $=cheerio.load(html); // creates new cheerio object, what also contains document (root)
const elem = cheerio(elem); // creates new cheerio object, what only contains this element 
```
I am not very good at explanation, but maybe helps
