### ISSUE TITLE
New type definition does not reflect API for children

### ISSUE THREAD

**Issue by bodinsamuel** [cheeriojs/cheerio#1854]
Hello,
Thanks @fb55 for the Typescript migration,
I'm trying to test the release, I think I have found an issue but let me know if it was intended.

When selecting and returning children, typescript will complain that some props do not exists, but they do.

- [Typescript Playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=17&pc=37#code/JYWwDg9gTgLgBAYwBYFMVWBOAzKERwBEyaGEhA3AFBUIQB2AzvACRwC8iq6mAdADYQAhgBMAFAAMAPEhgh+APikAjCCICeSkcABuSpAEZE-IY0btCMYDH4pCcEUJhCAtDBTML2COQUAhISgpIQcnV3dPQmVAwiUhJQB6eKkkxMNE7T0U1Q00uUUJABo4AG8qOAq4AH0AV0YUAAl8gAVA+qgAJgAuOBgoGpRC8sqRFDpRgFF6KysPHr6Bocq4emgQIX5gAC8UAHUkaw8wIQQUHuwN+qXKgA95AFk1M5xLweGAXwBKaloGZjgWCh+BwAWIAOS8Ga2MHfX5MeDYYBQZgAYQO-BEIMB-F4dGmKGmjDEnwA2gYALo-PGMCC2AQQADmYkIBkIxWxvEczmJnzhNLpgiZhC5QjZOCRqPRIk5YV51NpKHpQvoQhAdmKiORMDRwAxvBVarlfwVSuZyF1IigBLFmslFtxUqt9CNTBNguZMHUYHV4q1Or1nu9nyAA)
- [RunKit Repro](https://runkit.com/5f63d2c90961f0001a0e31b3/60991bd11fe339001956bbe2)

Can you provide some guidance here? Maybe it was on purpose.
Thanks a lot

**Comment by fb55** [comment]
Hi @bodinsamuel, this is intentional. `contents` returns all of a node's children (tags, text etc.), so you will have to add type checks to make sure everything has the expected type. The `prop` method should come in handy here as well.

You can also force types if you know how the markup is going to look; I've updated your playground to reflect this: [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wMYAsCmOrARwBmUEIcARNngRJQNwBQTGEAdqvACRwC8mXPkIA6ADYRkAEwAUAAwA8WGCDEA+BQCMIUgJ4apwAG4asARkxi0qPpRjAYYnJThTkMZAFoYOLreIQ9GoAQshQCsiu7l4+fpSaYZQayBoA9CkK6WnmaYYmmdp62SrqcgA0cADeTHC1cAAeqgBcVTV1tVI4bJ0Aouz29r4tMFAArjhlbe3s0CDIYsAAXjgA6lgOvmDIGDgtxPOoE1N1jWIAsjq7JAc4xwC+bXcAlMysHFxw3Dhi-J8yAOQiAZOf4vN6ceDEYBQLgAYXWYikvy+YhEbH6OH6qBkTwA2mYALoodA0YQQEQ9JwgTEwV7o1AQJziCAAcxklDMlAqKJEbg8OKeTFSqTgABVcHA5HzkHI4GAyGB8DBdHBgOgZBhRlAoDSxLonqqMVB2PMUOwkTN4Dh6pBDlIROCGUyJGzKNKuXAZFCYTB4cBEcSzfredFBfTGThma6TdSPd64Qj7TGcGH3hGo+zsP6pDr2HHoQns2jE7nU5x0y72crFfmfX7EUDdIqnkA)

Cheerio currently doesn't expose the type check utilities; they are implemented [in domhandler](https://github.com/fb55/domhandler/blob/5883837c364d087f2d0df07f91031ecbf46a9554/src/node.ts#L244-L298). I am contemplating re-exporting them from Cheerio, but haven't made up my mind yet.

**Comment by fb55** [comment]
> what is the true difference between a Node and an Element?

These names are taken directly from the W3C DOM spec, but I agree that we should explain this better. I have added some short descriptions to the `domhandler` module (see https://github.com/fb55/domhandler/commit/2475d2e0285f94947081748c17348ccd312ca6b1), but we should invest in some proper docs soon.

> Also it seems that string template confuse the type

This is actually a shortcoming of the current TS version, and a `as const` fixes it; see [this Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wMYAsCmOrARwBmUEIcARNngRJQNwBQTGEAdqvACRwC8mXPkIA6ADYRkAEwAUAAwA8WGCDEA+BQHplqtXIA0cAN5M4ZuAA9VALmOnzZqTjZOAouxjBPOVLZhQAVxx9ewd2aBBkMWAALxwAdSwvHzBkDBxbYijUYNDzKzEAWQgnTOycPIBfe0qASmYmTU04ABUk9GB0ZDgAORKcOAAjAPhULAgAsSkhgdcxHBAcD1YOLjhuHDF+dfksbiMARkq5FHQ2Thh6pmBiOBkNsXElgHMYLDg1OAAGWrszc7WxGAUDWAgeIiBIJgMiu-1WEHm4ggzxklBgAE8wDhKIZwakoEsYKgYSIsGgZJCuABtL4AXVqV2qjWabU6cDZyHYcDmC0JKwu602ACZttwZAByLAHcVXG53B5Cp7sV7vT4-P6YVbwSnwMHCiHArgw5hwzgInBIlFozHY3H6-GE4m1UnknU0+mMlhNVrtdldLk8xbLAE8TYAZlFEtJ0tlt3u4aVKo+31+JlNgMNusFYjDBqhxvsAPNltRGKxOOzuYdHidLuJbrpDOYTO9rI6-u58yDMH5aweABZI+Lo8mpTLmHL42J+4m3sn1WnNQKdaLNjOdQX08WJFay7bszPq0SSWT65n3U2mEygA). This should be fixed with the next TS version.

**Comment by sartoshi-foot-dao** [comment]
While using `.each` iterator, checking `el.type === 'text'` turned off Typescript warnings for me. Hope this helps someone.

```
const $ = cheerio.load(html);

$({h1 > p}).contents().each((i, el) => {
  if (el.type === 'text') {
    console.log(el.data);
  }
})

```

**Comment by fb55** [comment]
Tagged unions were added in the last release, which should make the types easier to consume. Also, the `Node` type was replaced with `AnyNode`, which should make the difference to `Element` obvious.
