### ISSUE TITLE
After the release of `v1.0.0-rc.11`, `Module parse failed: Unexpected token` occurs

### ISSUE THREAD

**Issue by ygnoh** [cheeriojs/cheerio#2545]
As the title says, since `v1.0.0-rc.11` the below error occurs:
```
START:
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
✖ ｢wdm｣: 
ERROR in ./node_modules/htmlparser2/lib/esm/index.js 59:9
Module parse failed: Unexpected token (59:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     return getFeed(parseDOM(feed, options));
| }
> export * as DomUtils from "domutils";
| // Old name for DomHandler
| export { DomHandler as DefaultHandler };
 @ ./node_modules/cheerio/lib/esm/index.js 11:0-68
 @ ./node_modules/enzyme/build/ReactWrapper.js
 @ ./node_modules/enzyme/build/index.js
 @ ./test.entry.js
```

I think it's a bug of `cheerio`, because it has been occurring since 3 days ago when the `v1.0.0-rc.11` released.

Could you please look into this bug?

**Comment by fb55** [comment]
The bundler is choking on `export * as DomUtils from "domutils";`. It seems like Webpack has supported the `export * as ...` syntax since ~2020 (see https://github.com/webpack/webpack/commit/3cf8299602b468ae0291779cd57c7fed3037b7f6), and an update should fix things. Alternatively, you could also force the bundler to pick up the CommonJS code that's still shipped with Cheerio.

For https://github.com/umijs/umi/issues/8109: umijs seems to have switch to rollup afaict (at least I haven't been able to find a Webpack version), so there is a chance that updating some internal packages might do the trick?

Please let me know if this makes sense!

**Comment by nicolashu** [comment]
same issue

**Comment by mike-lischke** [comment]
People might no be able to upgrade Babel, if that's actually brought in by other modules (e.g. via create-react-app). Changes that require upgrades of other libraries should always be accompanied by at least a minor version increase.

**Comment by ygnoh** [comment]
@mike-lischke How can I lock the package import to `1.0.0-rc.10`?

In my project, `enzyme` is using `cheerio`. I couldn't find a way to lock the subdependecy of `enzyme`.

**Comment by ygnoh** [comment]
I resolve this problem by declaring `cheerio` in `devDependencies` like:

```
  "devDependencies": {
    "cheerio": "=1.0.0-rc.3",
    ...
```

Hope this helps.

**Comment by bindoon** [comment]
I have the same issue. help me.

**Comment by gladson1976** [comment]
I've tried the suggestion by @ygnoh, and it works fine in my local build.. but fails in the GitLab pipeline..
anyone have any ideas ?

**Comment by yanglbme** [comment]
lock the version in dependencies, like this https://github.com/doocs/md/commit/551b07d46df7136e5758b418a62bcec3c9bb52f5

**Comment by bindoon** [comment]
it seems `enzyme` is using `cherrio`, how could I lock `cherrio` in `enzyme`

**Comment by gladson1976** [comment]
> it seems `enzyme` is using `cherrio`, how could I lock `cherrio` in `enzyme`

lock the cheerio version in your base package.json in dependencies or in devDependencies.. set it to "cheerio": "1.0.0-rc.10"

**Comment by gladson1976** [comment]
> lock the version in dependencies, like this [doocs/md@551b07d](https://github.com/doocs/md/commit/551b07d46df7136e5758b418a62bcec3c9bb52f5)

works fine when it is referenced in dependencies.. I had added in the devDependencies earlier..

**Comment by ygnoh** [comment]
@yanglbme @gladson1976 

As a side note, `enzyme` recommends to locking `cheerio` version as `=1.0.0-rc.3`.

https://github.com/enzymejs/enzyme/issues/2559#issuecomment-1133812922

**Comment by gladson1976** [comment]
> @yanglbme @gladson1976
> 
> As a side note, `enzyme` recommends locking `cheerio` version as `=1.0.0-rc.3`.
> 
> [enzymejs/enzyme#2559 (comment)](https://github.com/enzymejs/enzyme/issues/2559#issuecomment-1133812922)

Yes, they do.. but since it was working fine for me till Friday with rc.10.. decided to go with it..

**Comment by meeksfred** [comment]
> I resolved this problem by declaring `cheerio` in `devDependencies` like:
> 
> ```
>   "devDependencies": {
>     "cheerio": "=1.0.0-rc.3",
>     ...
> ```
> 
> Hope this helps.

Seriously a life saver, thank you.

**Comment by Livshitz** [comment]
+1 on the issue. Caused silent issues during builds. Was discovered only after an exhausting search as a dependency of a sub package, and most frustrating is that it was auto upgraded as rc11 treated as 'patch' (any default `^` package version will do that).
Semantic versioning isn't used by this project?

**Comment by francois06** [comment]
1.0.0-rc.11 is an issue for me because of the ECMAScript Modules used in parse5-htmlparser2-tree-adapter 7.0.0 ...

**The breaking change on parse5-htmlparser2-tree-adapter v7  is well documented  :** 
https://github.com/inikulin/parse5/releases/tag/v7.0.0 

This is a shame, that this package (cheerio) bump its dependencies (with major change) without a major change on its version .... It cost me hours of debugging -_-  

How i landed here ? 
I'm here because cheerio is a dependencies of an dependencies of MJML (that I use)!
(I remove node_modules and when I yarn install again because people do not handle correct semver everything explode)

Spend hours to find this => 
MJML > mjml-core > juice > "cheerio": "**^1.0.0-rc.10**"  > parse5-htmlparser2-tree-adapter 7.0.0

Cheerio go to 1.0.0-rc.11 with parse5 v7 ==> all lib which use "cheerio": "**^1.0.0-rc.10**" will potentially blow up ...

So, please next time read the changelog before up the dep... 

**Meanwhile, here my fix :** 

if you use yarn, add these lines in package.json : 
```
 "resolutions": {
    "cheerio": "1.0.0-rc.10",
    "parse5-htmlparser2-tree-adapter": "^6.0.0"
}
```

if you use npm, add these lines in package.json : 
```
 "overrides": {
    "cheerio": "1.0.0-rc.10",
    "parse5-htmlparser2-tree-adapter": "^6.0.0"
}
```


Ressources
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by fb55** [comment]
`parse5-htmlparser2-tree-adapter` is a dual ESM and CJS module and shouldn't need this workaround.

**Comment by Ganesh1991** [comment]
We getting the below issue while creating the build

```
./node_modules/html-to-react/node_modules/htmlparser2/lib/esm/index.js 67:9
Module parse failed: Unexpected token (67:9)
You may need an appropriate loader to handle this file type.
return getFeed(parseDOM(feed, options));
export * as DomUtils from "domutils"; // Old name for DomHandler
 export { DomHandler as DefaultHandler };
```

We tried updating both devDependencies and dependencies with "cheerio": "1.0.0-rc.3" But still we are getting same issue

Any suggestions?

**Comment by ljharb** [comment]
@fb55 i don't understand - all you have to do is add an entry to "exports", which won't have a negative impact on literally anybody.

Also, not everyone uses bundlers - enzyme runs in node, for example.

**Comment by AnkurPrabhu** [comment]
> > I resolved this problem by declaring `cheerio` in `devDependencies` like:
> > ```
> >   "devDependencies": {
> >     "cheerio": "=1.0.0-rc.3",
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps.
> 
> Seriously a life saver, thank you.

yes the equal to sign "=" in the statement helped me solve my issue too thankyou

**Comment by HondryTravis** [comment]
god

**Comment by vlad-frontdev** [comment]
> Lock the dependency to a version that still uses htmlparser2 v7

Just my 2 cents here basing on [this comment](https://github.com/cheeriojs/cheerio/issues/2545#issuecomment-1183477852). For me locking `htmlparser2` dependency to `~7.0.0` in `package.json` `resolutions` did the trick. If you're using Yarn you can try out this.

```
"resolutions": {
    ...
    "htmlparser2": "~7.0.0"
}
```

**Comment by seanhexl** [comment]
> > Lock the dependency to a version that still uses htmlparser2 v7
> 
> Just my 2 cents here basing on [this comment](https://github.com/cheeriojs/cheerio/issues/2545#issuecomment-1183477852). I'm not a `cheerio` but `htmlparser2` user. For me locking `htmlparser2` dependency to `~7.0.0` in `package.json` `resolutions` did the trick. If you're using Yarn you can try out this.
> 
> ```
> "resolutions": {
>     ...
>     "htmlparser2": "~7.0.0"
> }
> ```

Can confirm this also worked for me (for me `htmlparser2` is coming from `sanitize-html`, but we also use `enzyme` on its own). I was testing resolving `cheerio` and `parse5-htmlparser2-tree-adapter`, but I no longer need to - resolving `htmlparser2` is enough by itself.

**Comment by ItzLarz** [comment]
I want to emphasize that this is **not** a cheerio issue. The issue lies in the newest version (8.0.1) htmlparser2 dependency, which has a file using syntax webpack doesn't understand. So to fix the issue check if any of your dependencies is using that version of htmlparser2 by running:
`npm ls htmlparser2`
Revert all those dependencies to previous versions where they use htmlparser2 version 7.2.0 or less.

**Comment by fb55** [comment]
To add to @ItzLarz: Modern versions of Webpack do understand the relevant syntax, so an upgrade will resolve this issue as well. See https://github.com/fb55/htmlparser2/issues/1237#issuecomment-1182522861 for more solutions.
