### ISSUE TITLE
$.html() encoding apostrophes

### ISSUE THREAD

**Issue by eddiemonge** [cheeriojs/cheerio#319]
Having quotes in quotes and calling html on it encodes the inside quotes. jQuery .html correctly returns the desired output (not replace `'` with `&apos;`)

``` js
console.log(require('cheerio').load('<div ng-include="\'views/main.html\'"></div>').html());
// <div ng-include="&apos;views/main.html&apos;"></div>
```

**Comment by psolbach** [comment]
This is still an issue introduced by /fb55/entities. A PR solving this issue was made in 2015 and remains unmerged. Scenario here: Corporate email that contains stuff parsed by cheerio, `&apos;` renders as plaintext in Outlook environment. What should we do about it? As a cheerio user, I do not have control over whether `entities` does HTML4 or HTML5 encoding.

**Comment by soanvig** [comment]
I had `style="font-family: 'Roboto';"` and `{ decodeEntities: false }` fixed `%apos` problem

**Comment by Deykun** [comment]
The problem with `&apos;` is that it is part of XHTML standard not HTML.
