### ISSUE TITLE
map returns array instead of Cheerio object

### ISSUE THREAD

**Issue by ysulyma** [cheeriojs/cheerio#323]
In jQuery, `$(selector).map(callback)` will return a jQuery object wrapping return values of `callback`. In Cheerio, we instead get back an array, each element of which is a length-1 Cheerio object wrapping a return value of `callback`.

**Comment by jugglinmike** [comment]
Convert the collection to a JavaScript array first:

    $('div').map(($el) => {
      // $el is a Cheerio object
    });

    $('div').toArray().map((el) => {
      // el is a node
    });

Note that the return value will also be an array, though!

**Comment by discopatrick** [comment]
> 1. It's consistent with jQuery (therefore portable and familiar). I still maintain that making jQuery code portable is a valid use case for this project.
> 2. It's more efficient--not all users will need Cheerio instances, and those that do can create a Cheerio object from the nodelike themselves: `var $elem = Cheerio(this);`

Hi @jugglinmike - I'm in agreement with the two points you make. However, I would like to ask for some advice on how to implement your point 2.

Firstly I'm assuming that `Cheerio` in your example is the result of `cheerio.load(html);` (given that `const cheerio = require('cheerio')`), which would have been executed at some point before moving into the `map` callback.

Given that assumption, in order to rewrap the node in a cheerio object doing `var $elem = Cheerio(this);` as you describe, I would need to have the `Cheerio` var in scope, or alternatively have the original `html` var in scope so that I could recreate the `Cheerio` object with another `cheerio.load(html);`. Unfortunately in my code I have neither of these vars in scope at the time I wish to do this. Thus, I am using this little hack:

```js
// inside a class

startHere() {
  const html = '<html>...</html>' // loaded from disk in reality
  const $ = cheerio.load(html);
  const $interesting = $('div#interesting');
  this.doSomething($interesting);
}

doSomething($interestingElement) {
  // note that neither `$` nor `html` are in scope here
  $spans = $interestingElement.find('span');
  $spans.map((i, el) => {
    const $ = cheerio.load(''); // here's the hack - call `load` with empty string
    const $el = $(el);
    // do something with $el now that it's wrapped in a cheerio object
  });
}
```

This seems to work fine. It just feels a little messy that I should need the hack. Can you think of a better way?

One solution might be to have `$` as a member of the class rather than creating it in `startHere()` so that I can call upon it with `this.$`, although the issue there is that this class works on multiple html documents (with different values of `html`) so if I call `this.$ = cheerio.load(html);` I would overwrite the previous value. That said, generally I do these operations in series and not in parallel, so perhaps it would be fine.
