### ISSUE TITLE
Rendering escapes non-ascii UTF-8 characters

### ISSUE THREAD

**Issue by ghostganz** [cheeriojs/cheerio#466]
When rendering with .html() any non-ascii character in an attribute (and elsewhere too probably) gets escaped with "&amp;#xXX;" codes, even though it's a valid UTF-8 character that doesn't need to be escaped.
This means that Swedish text is unnecessarily turned into ampersand salad.

**Comment by praestans** [comment]
@fb55 `decodeEntities: false`  is only suitable in some cases. Here is an example:
```
var cheerio = require('cheerio'),
    $ = cheerio.load('<p>ööööö &lt;p&gt; 穀書對 яяяяяя</p>');

console.log($.html({decodeEntities: false}));
console.log($.html({decodeEntities: true}));
```
result is the following:
> &lt;p&gt;ööööö &lt;p&gt; 穀書對 яяяяяя&lt;/p&gt;
> &lt;p&gt;&amp;#xF6;&amp;#xF6;&amp;#xF6;&amp;#xF6;&amp;#xF6; &amp;lt;p&amp;gt; &amp;#x7A40;&amp;#x66F8;&amp;#x5C0D; &amp;#x44F;&amp;#x44F;&amp;#x44F;&amp;#x44F;&amp;#x44F;&amp;#x44F;&lt;/p&gt;

The problem with all special characters that needed to be replaced!

I made a fast fix locally in node_modules/cheerio/node_modules/entities/lib/encode.js by commenting out `.replace(re_nonASCII, singleCharReplacer)` in
```
return data
	.replace(re, func)
	.replace(re_astralSymbols, astralReplacer)
	.replace(re_nonASCII, singleCharReplacer);
```
It would be great to extend functions in entities project with options for selecting replacements. And transfer these options into cheerio.

**Comment by fb55** [comment]
You need to pass the option to load.
>
>

**Comment by praestans** [comment]
> You need to pass the option to load.

@fb55, I do not agree that it is a good solution. I have the following considerations:

1: The problem is with output only. Before loading one could have no idea about the desired output format. Moreover several types of output may be demanded.
2: Using `decodeEntities: false` in load can ruin all the subsequent manipulation logic. For example, compare the output of the following lines:
```javascript
console.log(cheerio.load('&lt;p&#62;', {decodeEntities: false}).root().text());
console.log(cheerio.load('&lt;p&#62;', {decodeEntities: true}).root().text());
```
3: This point is connected with the previous one. All strings in Javascript and Node.js are Unicode-compatible, so it is a good practice to convert all literals to Unicode (utf-16, utf-8) before processing them. With `decodeEntities: false` we have strings in dual format: Unicode with internal encoding. This could easily confuse.

**Comment by fb55** [comment]
That's only a problem when using cheerio inside a console, and you're able
to just execute the commands again, changing the load call. IMHO not a
problem.

**Comment by carterh062** [comment]
I am using Cheerio 0.15.0 (0.12.0 was too old and would have required a lot of changes), and it is working fine.
