### ISSUE TITLE
.text() breaks with text nodes and tables

### ISSUE THREAD

**Issue by aroman** [cheeriojs/cheerio#546]
this has been reported in various ways in other bug reports, but basically .text() breaks with text nodes inside `td`s that occur before `th`s. The result is that .text() on a td spills over to it's siblings further down the DOM tree.

I came up with this workaround, in the meantime:

``` javascript
function betterText(element) {
    return _.reduce(element[0].children, function (memo, child) {
        return child.type === 'text' ? memo + child.data : memo; 
    }, '');
}
```

**Comment by Romick2005** [comment]
I think the problem here is that .children and .children() returns different amount of nodes.
`var $ = cheerio.load("<table><tr><td>td text<b>Bold</b>Text after</td></tr></table>");
const cells = $("table td");
const len = cells.length;
for (let i = 0; i < len; i++) {
  const cell = cells[i];
  const cellNodes = cell.children;
  const cellNodesCount = cellNodes.length;
  for (let j = 0; j < cellNodesCount; j++) {
    cellNode = $(cellNodes[j]);
    console.log("cell.children - cellNode: " + cellNode.text());
  }

  const cellChildren = $(cell).children();
  const cellChildrenCount = cellChildren.length;
  for (let j = 0; j < cellChildrenCount; j++) {
    cellNode = $(cellChildrenCount[j]);
    console.log("$(cell).children() - cellNode: " + cellNode.text());
  }
}
`

**Comment by fb55** [comment]
@Romick2005 `.children()` filters for tags.

I'm also unsure what the original issue is, let's hope it has been resolved!
