### ISSUE TITLE
Undocumented attribs property safe to use?

### ISSUE THREAD

**Issue by jtrussell** [cheeriojs/cheerio#547]
I was looking for a way to move all of one element's attributes to another element and noticed the `attribs` property on cheerio elements which seemed to be exactly what I needed but it's not documented anywhere that I could see. It is however used in the example in [htmlparser2's readme](https://github.com/fb55/htmlparser2/) so I'm wondering if this property is safe to use of if there's a better way getting at all attributes.

**Comment by e2tha-e** [comment]
I hope we can get some finality on this, as I'm sure a number of projects (mine included) depend on consistency with the `.attribs` property.

I find myself revisiting issues like this because of the unofficiality of `.attribs` and the concerns that arise when new Cheerio versions are released.

For the time being, even though Cheerio v1 RCs parse with parse5 by default, they still uses htmlparser2's treeAdapter to write attribute data to the `.attribs` property, irrespective of the parser.  

https://github.com/cheeriojs/cheerio/blob/v1.0.0/lib/parse.js#L28

The question on why `.attribs` and not `.attributes` is answered in https://github.com/fb55/htmlparser2/issues/35 - basically backward compatibility with htmlparser, the precursor to htmlparser2. According to @fb55 "that ship has sailed a long time ago."

Can we publicly document that finality in Cheerio as well?

**Comment by fb55** [comment]
Assuming TS types took care of this one.

**Comment by JamesMGreene** [comment]
To clarify on that unfortunately cryptic closure message, it would appear that ther TypeScript type definitions show an `attr()` method that can be invoked without any arguments to return a simple object map of key-value pairs:

https://github.com/cheeriojs/cheerio/blob/a3363012de3ddf4dafe91e89864d8feca9d28722/types/index.d.ts#L18

As shown in tests also:

https://github.com/cheeriojs/cheerio/blob/a3363012de3ddf4dafe91e89864d8feca9d28722/test/api/attributes.js#L16-L20

**Comment by plocket** [comment]
I'm finding that currently `.attr('value')` and `.attribs.value` are returning two different things. Not sure if this is the right place to put this, but I found this thread while trying to find some context for this situation. I'm hoping this will help someone else with the same confusion in the future.

```js
const cheerio = require('cheerio');
const html = '<input class="my_inputs" type="checkbox">';
const $ = cheerio.load( html );

let node = $( '.my_inputs' )[0];
let $node = $( node );
console.log( node.attribs.value );  // undefined
console.log( $node.attr( 'value' ));  // 'on'
```

`.attr('value')` returns 'on' while `.attribs.value` returns undefined. If you're looking for the 'real' `value` attribute, `.attribs.value` seems to give the most accurate to me at the moment for what it's worth.

Again, not necessarily reporting a bug, just hoping to help some future person figure out how to get the actual HTML attribute value with cheerio.
