### ISSUE TITLE
Ignoring ejs script tags (ejs)

### ISSUE THREAD

**Issue by tobinharris** [cheeriojs/cheerio#579]
Is it possible for cheerio to handle or ignore ejs tags like `<% ... %>`. I'm finding when I call `$.html()` it mangles the contents.

Great lib though :)

**Comment by furqanZafar** [comment]
+1

Possible workaround:
1) replace ejs tags with html comments 
```javascript
str.replace(/<%((.|\s)*?)%>/g, function(match, subMatch){ return "<!-- <%"+subMatch+"%> -->" });
```
2) perform jquery operations ... $("head").append($("<script/>").attr("src", "http://dynamic.js")); ...
3) remove the comments from the ejs tags
```javascript
$.html().replace(/<!-- <%((.|\s)*?)%> -->/g, (match, subMatch){ "<%"+subMatch+"%>"});
```

**Comment by mbernath** [comment]
+1

For those who also have EJS code within attributes, e.g.```<img src="<%= pictureUrl %>" alt="">```, here is another workaround:

      var ejsCache = [];
      html = html.replace(/<%(.*?)%>/g, function (match) {
        ejsCache.push(match);
        return 'cachedejsstart' + (ejsCache.length-1) + 'cachedejsend';
      });
      // ... Perform operations here ...
      html = html.replace(/cachedejsstart(\d*)cachedejsend/g,function (match, num) {
        return ejsCache[parseInt(num)];
      });

**Comment by intmainreturn0** [comment]
For previous answer: better to use regexp `/<%([\w\W]*?)%>/g` instead of `/<%(.*?)%>/g` in case of multiline ejs entries.

**Comment by ryangall7** [comment]
+1

**Comment by fb55** [comment]
Cheerio won't support markup that isn't HTML out of the box.

**Comment by ericuldall** [comment]
Not sure the last comment addresses the problem here... The problem is if you want to use cheerio to do work on an EJS file it breaks the EJS tags.

Example Input:
```
<div><%= myVar %></div>
```

Cheerio Output:
```
<div>&lt;= myVar %&gt;</div>
```

Now EJS is no longer able to successfully compile that value. I think the real problem is that cheerio insists on html encoding everything without the consent of the end user. It should be something we could turn off. 

```
$.html({ encodeEntities: false });
```

Is there a way to disable that currently?
