### ISSUE TITLE
Auto-Correcting Markup

### ISSUE THREAD

**Issue by MCTaylor17** [cheeriojs/cheerio#580]
I'm loving this tool, but had a quick question about the output.

I have:

```
<ul>
    <li>a list item <li>with a weirdly nested list item</li> and more text afterwards</li>
</ul>
```

Which renders to:

```
<ul>
    <li>a list item </li>
    <li>with a weirdly nested list item</li> and more text afterwards
</ul>
```

I'm trying to catch poorly structured markup like this using $("li > li").addClass("attn") so that it can be reviewed and fixed manually.  Unfortunately, this auto-correction actually obscures the error and makes it harder to find.

Is this intentional behaviour?

**Comment by wahengchang** [comment]
#Please help

I got the same issue, i dont know a way to parse the nest structure:



```html

<ul class="class1">
  <li>
     <div class="title">title1</div>
        <ul class="class1">
            <li>nickname1</li>
            <li>nickname2</li>
          </ul>
  </li>
</ul>

```

**Comment by sholladay** [comment]
Hi @wahengchang if you are experiencing some kind of problem, it looks like a different issue.

Whereas the OP was hoping for a way to turn off Cheerio's "auto-fixing" behavior that corrects invalid markup, your markup is already perfectly valid - I double checked by reading the spec and trying it in the W3C validator, just to be sure.

What problem are you having exactly? You should probably open a new issue for it, since this one is closed and therefor won't receive much attention.
