### ISSUE TITLE
error when loading cheerio

### ISSUE THREAD

**Issue by cthorner** [cheeriojs/cheerio#654]
I'm sure this the problem is between the seat and the screen on this one, but maybe the doc could be improved to help others as well.

I'm getting this error:

Uncaught Error: Module name "parse" has not been loaded yet for context: _. Use require([])

from line 5 of cheerio.js when loading cheerio. Here is what's on line 5:

var parse = require('./parse'),
    _ = require('lodash');

I am using the bower package(maybe that is the problem?).

**Comment by jugglinmike** [comment]
This looks like a problem with RequireJS pathing. I wouldn't recommend this approach, though, as Cheerio's internal modules are not intended for direct access. If you want to work with the library, then require it's top-level module. Make sense?

**Comment by jugglinmike** [comment]
Scratch that, I see now that you have shared code from Cheerio itself, not your own application.

The problem here is that Cheerio is not an AMD module, so your AMD loader (RequireJS in this case) cannot correctly resolve its internal modules. I don't think this is a documentation issue because there is nothing in our documentation to suggest that the library can be loaded in AMD contexts.

If you would like to use Cheerio in a browser, check out [Browserify](http://browserify.org/)

**Comment by jugglinmike** [comment]
It's been a few weeks, so I assume Browserify worked out for you. If that's not right, let me know and we'll re-open this issue.

**Comment by cthorner** [comment]
Thanks for the feedback. Much appreciated. I haven't tried browserify, but that looks like it would work. Agreed on closing this.
