### ISSUE TITLE
Deferred

### ISSUE THREAD

**Issue by garygreen** [cheeriojs/cheerio#712]
Is it possible to support [$.Deferred](https://api.jquery.com/category/deferred-object/) from jQuery? Apologies if it's been mentioned before but can't find any previous issues and limited stuff about it on the internet. There is [Q](https://github.com/kriskowal/q) but not entirely sure how to integrate.

**Comment by jugglinmike** [comment]
We don't have any plans to implement support for parts of the jQuery API that do not concern the DOM, since we prefer to stay focused on DOM traversal/manipulation and let consumers choose Node.js equivalents for other functionality. So Q may be a good choice for you; I haven't tested this, but it may be as simple as:

```js
var cheerio = require('cheerio');
var $ = cheerio.load(/* your markup here */);
$.Deferred = require('q').defer;
```
