### ISSUE TITLE
Cannot wrap root

### ISSUE THREAD

**Issue by adamgruber** [cheeriojs/cheerio#737]
Is it possible to wrap the root object?

```
$.root().wrap('<div />')
```

This throws an error `... has no method 'wrap'`

**Comment by jugglinmike** [comment]
Short answer: "no".

Long answer: the error you have reported is not related to the root node at all. "has no method 'wrap'" means that there is no function property on the object at the key "wrap". That's because the latest version of Cheerio does not include that method--it will be published in the next release.

But even then, you will have a tough time doing this. The "root" node is not an element and isn't really intended to be manipulated in this way. I can't say for sure, but I suspect you would like to wrap the top-level element in your document. This is stored as a child of the root node, and you could wrap *that* with code like this:

```js
$($.root().children[0]).wrap('<div>');
```

but again, not until the next minor release of Cheerio. (If you'd like to use the `wrap` method before that release, you might try using a git URL in your `package.json` file. Read more in this section of the npm documentation: [package.json: Git URLs as Dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).)
