### ISSUE TITLE
Introducing recognizeSelfClosing mode for Cheerio

### ISSUE THREAD

**Issue by ramakrishnan** [cheeriojs/cheerio#766]
I see few issues related to self-closing tags in this project, even I experienced a similar situation on self-closing tags.

Though as per HTML 5 standards having closing tags are options, but in of my legacy project I had to keep few tags with a '/>'

I introduced `recognizeSelfClosing` as an extra option for `cheerio` and updates `dom-serializer` at https://github.com/cheeriojs/dom-serializer/pull/22

This change will ensure all self-closing tags have `/>` to its end.
Example
```html
<br/>
<input type="text"/>
<link href="something"/>
```
Please let me know if this makes sense and merged to  `dom-serializer`

**Comment by smaxtastic** [comment]
@ramakrishnan: On a similar note: Right now Cheerio seems to delete trailing slashes: `<img ... />` becomes `<img ...>`. But this is messing with some SVG elements. Is there a way to keep the trailing slashes? xmlMode is not an option, because that introduces a whole bunch of `</img>` tags.

**Comment by ramakrishnan** [comment]
@smaxtastic For that very reason I introduced `recognizeSelfClosing` in cheerios' dom-serializer. This mode ensures all self closing tags has a `/>` to their end.

**Comment by smaxtastic** [comment]
Okay, I thought so. But it hasn't been merged, right? I am also confused regarding the `recognizeSelfClosing` option in cheerio's underlying [html2parser](https://github.com/fb55/htmlparser2/wiki/Parser-options#option-recognizeselfclosing), since [it doesn't seem to work as expected](https://github.com/fb55/htmlparser2/issues/84) be some (including me).

**Comment by ramakrishnan** [comment]
I made the changes to dom-serializer to read the `recognizeSelfClosing` options set from cheerio to make changes for the closing tags. The pull request is yet to be merged. 
As dom-serializer is not watched by many so started a thread here. I want people to review the change and make it a part of cheerio.

**Comment by smaxtastic** [comment]
Awesome, looking forward to the merge, since that causes problems for people using void SVG elements (like `path`) in combination with my [grunt-responsive-images-extender](https://github.com/smaxtastic/grunt-responsive-images-extender) plugin.

**Comment by ramakrishnan** [comment]
@smaxtastic Could you let me know if you scenario i mean your i/p html string and your expected output. I can a do quick test in my code (https://github.com/cheeriojs/dom-serializer/pull/22)  and let you know.

**Comment by smaxtastic** [comment]
So according to [this issue](https://github.com/smaxtastic/grunt-responsive-images-extender/issues/4), the problem lies with

```html
<path d="something" />
```

which should be **leaved untouched**, instead cheerio turns it into:

```html
<path d="something">
```

That is undesired behavior since it screws up the SVG. Thanks for your help, highly appreciated!

**Comment by fb55** [comment]
@smaxtastic That was fixed by https://github.com/cheeriojs/dom-serializer/pull/17. 

`recognizeSelfClosing` is already present in cheerio as a parsing option – having the same option for the renderer is probably a good idea, although that should be discussed in the repo. I've explained in the PR why I didn't pursue it further. If anyone wants to open another PR, they welcome to do so.
