### ISSUE TITLE
Reference to $

### ISSUE THREAD

**Issue by rstacruz** [cheeriojs/cheerio#792]
If I have a Cheerio object:

```js
$list = $('ul#ingredients')
```

Is there a way to access `$` from $list? To be specific, I'd like to do this:

```js
$list.map(function (i, item) {
  var $item = $(item)
  // ...
}).get()
```

...but if I do that inside a function, it needs to know about `$`.

**Comment by jugglinmike** [comment]
Our goal is compatibility with jQuery, so my recommendation would be to use the same approach you would use with that library. There are two options that come to mind:

1. Access the function using the `constructor` property of an instance: `var $item = $list.constructor(item);`.
2. Pass an explicit reference to the "loaded" Cheerio function (`$` in your first code sample) with the `$list` variable

I would strongly encourage option 2. It requires your code to be a little more verbose, but that's largely the point. (This is generally not so much of a hassle using jQuery in the browser because the jQuery function assumes the current DOM is the document, so there is only ever one function to worry about.

**Comment by rstacruz** [comment]
the approach with jQuery would be to load `$` from `require('jquery')` or `window.jQuery`, so there's no need to track the existence of `$`. in Cheerio however, multiple `$`s can exist, especially if you're parsing many documents asynchronously, so I can't exactly "use the same approach."

I think having a reference to `$` would help solve a problem that only manifests in Cheerio (dealing with multiple documents), and not jQuery.

**Comment by jugglinmike** [comment]
Glad it helped!
