### ISSUE TITLE
Feature Request: add exists() function

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [cheeriojs/cheerio#798]
Wanted to check if you can add exists function to check if the element is present or not, currently using length for check?

elemnt.find("li").length instead 

element.exists("li") return true/false.

**Comment by sehrgut** [comment]
```.exists()``` is not part of the jQuery API, which Cheerio implements. Using ```.length``` is best practice.

**Comment by alanev** [comment]
Also you can write tine plugin for your own project:
```js
$.prototype.exists = function (selector) {
  return this.find(selector).length > 0;
}
$(element).exists('li');
```

**Comment by jugglinmike** [comment]
That's good reasoing, @sehrgut and good advice @alanev! Thanks to you both

**Comment by awb99** [comment]
I like the exists function. Would I  put this definition after I load the document via  $ = cheerio.load(data);

**Comment by sehrgut** [comment]
@awb99 Yes. See the section "Plugins" at https://github.com/cheeriojs/cheerio .

**Comment by mudlabs** [comment]
Length is always `0` for me?

```js
// I know it exists.
$("head").find("meta[name=description]").length; // 0
// I know it doesn't exist.
$("head").find("meta[name=blahblah]").length; // 0
```

**Comment by mudlabs** [comment]
You need to specify `{ xml: true }` in the load function.
- https://github.com/cheeriojs/cheerio/issues/1663#issuecomment-757120416

**Comment by 5saviahv** [comment]
One option If you use just fragments of html document tell it to cheerio by setting **isDocument** false.

``` js
const cheerio = require('cheerio');

const $ = cheerio.load(html, {}, false);
```

**Comment by mudlabs** [comment]
@5saviahv that's what I had previously. It still did not work as expected until I specified; 
```js
cheerio.load(html, { xml: true }, false);
```

**Comment by 5saviahv** [comment]
My comment was simply for extension to #1663 where they used only parts of table, in real world table cell cant exist without table.

Parsing tries to be as close to how browser handles html as possible. So when using `isDocument = false`, your html string may not contain tags **html**, **body**, **head**. Since they are document level tags and will be ignored. In result if you try now search `$("head")`. it returns empty because **head** tag is not present.

Also worth mentioning **isDocument** will be ignored when you use **xml**, since document level is simply not present, in this case.
