### ISSUE TITLE
Incorrect structure for the next siblings of a self-closing tag

### ISSUE THREAD

**Issue by eGust** [cheeriojs/cheerio#961]
If some siblings are above a self-closing tag, they will become children of the self-closing tag. 

A simple example tested in 0.22.0:
```jsx
const $ = require('cheerio')
const XML = `
<container>
  <tag />
  <child>1</child>
  <child>2</child>
</container>
`
console.log($(XML).children().length) // should 3, but 1
console.log($($(XML).children()[0]).html()) // should empty, but both child1 and child2
```
Cheerio incorrectly parses it as:
```
container
  tag
    child(1)
    child(2)
```

It also causes direct children selector ( >children ) not working in that scenario. 

P.S. the same code works fine in jQuery

**Comment by rickyblaha** [comment]
There is an option called `xmlMode` that defaults to false, meaning that cheerio only knows about regular HTML tags. If you were to change your example `<tag />` to `<img />`, then cheerio does recognize 3 child nodes since the img tag is expected to not have a closing tag.

But if you wanted it to accept any XML tags where any tag could be either empty or have a closing tag, rearrange this a bit and set the mode like this:

```
const cheerio = require('cheerio');

const XML = `
<container>
  <tag />
  <child>1</child>
  <child>2</child>
</container>
`;
let $ = cheerio.load(XML, {
  xmlMode: true
});
console.log($('container').children().length); // 3
```

**Comment by fb55** [comment]
Thanks @rickyblaha!
