### ISSUE TITLE
Is it possible to use cheerio inside a web worker ?

### ISSUE THREAD

**Issue by ghost** [cheeriojs/cheerio#98]

**Comment by ORESoftware** [comment]
I am running Cheerio on a Node.js server and looking to put the cheerio code inside a Webworker on node using https://www.npmjs.com/package/webworker-threads

if anyone has any advice on this, please advise ... not sure if I can use importscripts with cheerio on a Node.js server

**Comment by gebrits** [comment]
@ORESoftware interested in the Same. Ever got this to work?

**Comment by ORESoftware** [comment]
@gebrits actually I just used a child_process instead of a webworker. CP is a bit more memory and more expensive, but there's upsides to it to - simply much easier to import/require any code you want.

You can use the core cluster module like so:
https://nodejs.org/api/cluster.html#cluster_cluster_setupmaster_settings

or you can use my module "poolio", which can create a pool of worker processes tailored to whatever task you have.
https://github.com/ORESoftware/poolio

**Comment by gebrits** [comment]
thanks @ORESoftware. Totally missed the context here though. I was looking for a way to run cheerio clientside in a browser webworker.

**Comment by ORESoftware** [comment]
oh, well for the browser, why not just jquery?

I believe the raison d'être for cheerio is for serverside crawling. for
browser just use jquery or the like

**Comment by birla** [comment]
The DOM is not accessible inside a Webworker, hence the need for Cheerio.

**Comment by ORESoftware** [comment]
how do you load the DOM/HTML then? cheerio doesn't load the HTML just
parses it

**Comment by gebrits** [comment]
In a webworker HTML is available as a string after doing an ajax-call or
something. You could do cheerio.load(htmlString) similar as jquery(html).

Unfortunately, the latter breaks because among other things `window` and
`document` aren't unavailable which jquery builds on massively (e.g.:
`document.querySelector`)
